services:
  beatfilm-api:
    container_name: beatfilm-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - beatfilm-network

networks:
  beatfilm-network:
    name: beatfilm-network
    external: true
